name: Publish Python package

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
        
    - name: Build package
      run: python setup.py sdist bdist_wheel
      
    - name: Publish package
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: twine upload dist/*
      
    - uses: actions/checkout@v5
      with:
        uses: 'node20'  # Explicitly specify Node.js 20
  
    - uses: actions/setup-python@v5
      with:
        uses: 'node20'  # Explicitly specify Node.js 20
